---
- name: beaglebone wifi network config
  template:
    src: bb-wl18xx.j2
    dest: /etc/default/bb-wl18xx
    owner: root
    group: root
    mode: 0644
  register: wificonfig

- name: disable beaglebone services
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - bonescript-autorun
    - bb-wl18xx-bluetooth
    - apache2
    - cloud9.socket

- name: reboot and wait
  include_tasks: reboot_and_wait.yml
  when: wificonfig.changed
