---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - vim-nox
    - tmux
- name: colin
  user:
    append: yes
    generate_ssh_key: yes
    name: colin
    groups: "adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi"
    shell: /bin/bash
- name: colin ssh key
  copy:
    force: no
    src: colin-id_rsa.pub
    dest: /home/colin/.ssh/authorized_keys
    owner: colin
    group: colin
    mode: 0600
