---
- name: Install packages
  apt:
    name: ['git', 'vim-nox', 'tmux', 'xsel', 'liblo-tools', 'screen']
    state: present

- name: colin user
  user:
    append: yes
    generate_ssh_key: yes
    name: colin
    groups: "{{ user_default_groups }}"
    shell: /bin/bash

- name: colin ssh key
  copy:
    force: no
    src: colin-id_rsa.pub
    dest: /home/colin/.ssh/authorized_keys
    owner: colin
    group: colin
    mode: 0600

- name: beaglebone setup
  include_tasks: beaglebone.yml
  when: beaglebone

- name: yarn installed
  npm:
    name: yarn
    global: yes

- name: user systemd file directory
  file:
    path: "/home/{{ owa_deploy_user }}/.local/share/systemd/user/"
    state: directory
    owner: "{{ owa_deploy_user }}"
    group: "{{ owa_deploy_user }}"

- name: user jack systemd file
  template:
    src: jackd.service.j2
    dest: "/home/{{ owa_deploy_user }}/.local/share/systemd/user/jackd.service"
    owner: "{{ owa_deploy_user }}"
    group: "{{ owa_deploy_user }}"
    mode: 0644
  register: jackd_service

- name: systemd daemon-reload
  become_user: "{{ owa_deploy_user }}"
  systemd:
    scope: user
    daemon_reload: yes
  when: jackd_service.changed

- name: restart jackd user service
  become_user: "{{ owa_deploy_user }}"
  systemd:
    scope: user
    name: jackd.service
    state: restarted
  when: jackd_service.changed

- name: user jackd systemd units enabled
  become_user: "{{ owa_deploy_user }}"
  systemd:
    scope: user
    enabled: true
    name: jackd.service
