---
- name: sclang conf
  copy:
    src: sclang_conf.yaml
    dest: "/home/{{ owa_deploy_user }}/.config/SuperCollider/sclang_conf.yaml"

- name: update code
  git:
    repo: https://github.com/awakeningio/owa.git
    dest: "{{ owa_project_dir }}"
    clone: yes
    update: yes
    recursive: yes
  register: owa_git
  tags:
    - deploy_code

- name: update npm deps
  shell: npm install
  register: npm_finished
  failed_when: '"ERR!" in npm_finished.stderr'
  when: owa_git.changed
  args:
    chdir: "{{owa_project_dir}}"
  tags:
    - deploy_code

- name: update sc deps
  shell: sclang install.sc
  when: owa_git.changed
  args:
    chdir: "{{owa_project_dir}}"
  tags:
    - deploy_code

- name: owa environment
  template:
    src: owa_env.j2
    dest: "{{ owa_project_dir }}/owa_env"

- name: .supercollider.yaml for supercolliderjs
  copy:
    src: .supercollider.yaml
    dest: "{{ owa_project_dir }}/.supercollider.yaml"

- name: sync sounds
  synchronize:
    dest: "{{ owa_project_dir }}/"
    src: "{{ local_owa_sounds_dir }}"
    times: yes
    rsync_opts:
      - "--exclude=*.asd"
