arduino_ide_url: "https://downloads.arduino.cc/arduino-{{ arduino_version }}-linuxarm.tar.xz"
arduino_port: /dev/ttyACM0
arduino_version: "1.8.5"
owa_deploy_user: pi
fadecandy_config:
    listen: ["0.0.0.0", 7890]
    verbose: true
    color:
        gamma: 2.5
        whitepoint: [1.0, 1.0, 1.0]
    devices:
      -
        type: fadecandy
        map: [
          # [ OPC Channel, First OPC Pixel, First output pixel, Pixel count  ]
         #[ 0, 0, 0, 512 ],
          # [ OPC Channel, First OPC Pixel, First output pixel, Pixel count, Color channels  ]
#         [ 0, 50, 64, 12, 'grb' ]
          [ 0, 0, 0, 24 ],
          [ 0, 24, 64, 24 ],
          #[ 0, 48, 128, 24 ],
          #[ 0, 72, 192, 24 ],
          #[ 0, 96, 256, 24 ],
          #[ 0, 120, 320, 24 ]
          [ 0, 72, 192, 24 ],
          [ 0, 96, 256, 24 ],
          [ 0, 120, 320, 24 ],
          [ 0, 144, 384, 24 ],
          [ 0, 48, 448, 24 ]
        ]
nodejs_version: "11.x"
owa_environment:
  -
      name: GUI_OSC_IN_PORT
      value: 8989
  -
      name: GUI_OSC_OUT_PORT
      value: 8990
  -
      name: GUI_HOST
      value: csull-mbp
  -
      name: OWA_HOST
      value: localhost
  -
      name: SC_OSC_IN_PORT
      value: 8987
  -
      name: SC_OSC_OUT_PORT
      value: 8988
  -
      name: SOUNDS_DIRECTORY_PATH
      value: "{{ owa_project_dir }}/sounds"
  -
      name: FADECANDY_HOST
      value: localhost
  -
      name: DISABLE_LIGHTING
      value: 0
  -
      name: INPUT_ARDUINO_SERIALPORT
      value: "{{ arduino_port }}"
  -
      name: EXTERNAL_SC
      value: 0
  -
      name: DISABLE_GUI
      value: 1
  -
      name: DEBUG_INPUT
      value: 0
  -
      name: DEBUG_SC
      value: 1
  -
      name: DEBUG_LIGHTING_PERFORMANCE
      value: 0
