---
- hosts: all
  become: yes
  tasks:
    - include_role:
        name: base
    - include_role:
        name: colinsullivan.audio
    - include_role:
        name: geerlingguy.nodejs
    - include_role:
        name: colinsullivan.fadecandy
    - include_role:
        name: colinsullivan.supercollider
- import_playbook: site_deploy.yml
