---
- hosts: all
  become: yes
  tasks:
    - name: base packages
      include_role:
        name: base
    - name: install node
      include_role:
        name: geerlingguy.nodejs
    - include_role:
        name: colinsullivan.fadecandy
- import_playbook: site_deploy.yml
