@startuml

!include styles.puml

namespace owa {
  class OWAController {
    Top level entity for controlling everything.
    Entry point, starts all sub-controllers.

    OWAStateStore store
    inputController
    soundController
  }

  class SimulatorInputController {
    
    Converts messages from simulator UI into
    dispatched actions.

    oscActionListener
  }
  OWAController o-- SimulatorInputController
  
  /'class ArduinoInputController {'/
    /'Converts arduino inputs to dispatched actions.'/

    /'serialport.SerialPort arduinoPort'/
    /'..'/
    /'+ handleButtonMessage(data)'/
  /'}'/
  /'OWAController o-- ArduinoInputController'/
  
  class StateStore {
    Main state store for OWA app

    See data model for state tree.
  }

  class OSCActionListener {
    Forward actions from osc.js to a Redux state store.

    store
    oscSocket
  }

  class AbletonLinkController
  class SoundController
  OWAController *-- SoundController

  /'class OSCActionDispatcher {'/
    /'Redux middleware to dispatch actions via osc.js'/

    /'oscSocket'/
  /'}'/

  namespace simulator {
    class OWAUIApp {
      Entry point for the GUI

    }
  }

  namespace quarks.owa {
    class StateStore
    class OWAController {
      store
    }

    OWAController *-- StateStore
  }
  
}



@enduml
