@startuml

!include styles.puml

object InteractionState {
  levels = {levelID: LevelState}
}

object LevelState {
segments = [SegmentState]
}

object SegmentState {
bool isActive
}

InteractionState *-- LevelState
LevelState *-- SegmentState


@enduml
