@startuml

!include styles.puml

object OWAState {
  levels = {levelID: LevelState}
}

object LevelState {
segment = [SegmentState]
}

object SegmentState {
bool isActive
}

OWAStateStore *-- LevelState
LevelState *-- SegmentState


@enduml
