export const OWA_SOUND_BOOT_STARTED = "OWA_SOUND_BOOT_STARTED";
export const OWA_SOUND_BOOTED = "OWA_SOUND_BOOTED";
export const OWA_SOUND_INIT_DONE = "OWA_SOUND_INIT_DONE";
export const SESSION_PHASE_ADVANCED = "SESSION_PHASE_ADVANCED";
export const LEVEL_STOPPED = "LEVEL_STOPPED";
export const BUTTON_PRESSED = "BUTTON_PRESSED";
